//
//  RecycleInformation.swift
//  Recyche
//
//  Created by Zel Marko on 08/10/15.
//  Copyright © 2015 Giving Tree. All rights reserved.
//

let recycleCodesInfo = ["paper": "Newspapers, magazines, catalogs, White and colored paper (including lined, copier, and computer paper; staples are acceptable), Mail and envelopes (any color; window envelopes are acceptable), Paper bags, Wrapping paper, Soft-cover books (such as paperbacks and comics; no spiral bindings), telephone books", "metal": "Metal cans (including soup and pet food cans, empty aerosol cans, dried-out paint cans) Aluminum foil wrap and trays Metal caps and lids Household metal (such as wire hangers, pots, tools, curtain rods, knives, small appliances that are mostly metal, and certain vehicle license plates) Bulk metal (such as large metal items like furniture, cabinets, and large appliances) Empty and rinse containers before recycling.", "cardboard": "Cardboard egg cartons and trays. Smooth cardboard (such as food and shoes boxes, tubes, file folders, and cardboard from product packaging) Pizza boxes; remove and discard soiled liner, and recycle plastic supporter in your blue bin Paper cups (waxy lining is acceptable if the cups are empty and clean; plastic lids go in the blue bin) Corrugated cardboard boxes, flattened and tied", "glass": "Glass bottles, Glass jars, Empty and rinse containers before recycling.", "plastic": "Plastic bottles, jugs, and jars, Rigid plastic caps and lids, Rigid plastic food containers (such as yogurt, deli, or hummus containers; dairy tubs, cookie tray inserts, 'clamshell' containers, and other plastic take-out containers), Rigid plastic non-food containers, Rigid plastic packaging (such as “blister-pack” and “clamshell” consumer packaging, acetate boxes), Rigid plastic housewares (such as flower pots, mixing bowls, and plastic appliances), Bulk rigid plastic (like crates, buckets, pails, furniture, large toys, and large appliances), Empty and rinse containers before recycling.", "carton": "Food and beverage cartons (such as cartons for soy milk and soup), Drink boxes, Aseptic packaging, Rinse and place with your glass, metal and plastic recyclables."]

let recycleCodes = ["PETE SPI CODE: 1", "HDPE SPI CODE: 2", "PVC SPI CODE: 3", "LDPE SPI CODE: 4", "PP SPI CODE: 5", "PS SPI CODE: 6", "SHELF-STABLE CARTON", "REFRIGERATED CARTON", "GLASS GREEN", "GLASS CLEAR", "GLASS BROWN", "PAPER", "CARDBOARD", "NEWSPRINT", "ALUMINUM", "TIN OR STEEL", "PAINT OR AEROESOL CANS"]